### ISSUE TITLE
ctx.ResultBool(), ctx.ResultJson(), ctx.ResultDatetime() ? 

### ISSUE THREAD

**Issue by asg017** [riyaz-ali/sqlite#11]
Hey @riyaz-ali! After using this library for a ton of projects, I came up with a few "helper" functions that make some common tasks a tiny bit easier. If you think these would be nice, I'd be more than happy to make a PR to include them! And if you think it's too much of awkward, I'm also happy to shelve the idea away.

## `ctx.ResultBool()`

SQLite [doesn't have boolean datetypes](https://www.sqlite.org/datatype3.html#boolean_datatype), and instead uses `0` and `1` as alternatives.

**Proposal**: Add a new `ResultBool()` function that just results a `1` or `0`, like so:

```go
func (ctx Context) ResultBool(v bool) { 
  if v {
    ctx.ResultInt(1);
  } else {
    ctx.ResultInt(0);
  }
}

isUser := User.lookup(...)
ctx.ResultBool(isUser)
```

## `ctx.ResultJson(obj)`

SQLite stores JSON as text, and is marked with the special [subtype](https://www.sqlite.org/c3ref/value_subtype.html) of 74.

**Proposal**: A new `ctx.ResultJson` function that formats a given json.Marshable value into a JSON string, and also sets the correct [JSON subtype](https://github.com/sqlite/sqlite/blob/master/src/json.c#L89) for interoperability with other JSON functions like `json_object` and `json_array`

```go
func (ctx Context) ResultJson(value any) { 
   jsonBytes, err := json.Marshal(value)
   if err != nil {
    ctx.ResultError(err)
  } else if bytes.Equal(jsonBytes, []byte{"n", "u", "l", "l"} {
     context.ResultNull()
   } else {
     context.ResultText(string(b))
     context.ResultSubType(74)
   }
 }

ctx.ResultJson(string[]{"a", "b", "c"})
ctx.ResultJson(User)
ctx.ResultJson(nil)
```

One issue: the null check is a bit awkward, because `json.Marshall` will convert Nils into the literal text `"null"`, but I feel it should instead be a proper SQLite null. I also don't know if error'ing on any marshal error is the right move, but seems reasonable enough to me. 

## `ctx.ResultDatetime()` and `ctx. ResultDate()`

SQLite also doesn't have date data types, but is stored as [specific timestamps formats](https://www.sqlite.org/lang_datefunc.html). We could add a wrapper to convert Go `time.Time` and `time.Date` objects into SQLite timestamp formats. 

**Proposal**: Add a new `ctx.ResultDatetime()` that converts `time.Time` to `YYYY-MM-DDTHH:MM:SS.SSS`

```go
// timestamp layout to match SQLite's 'datetime()' format, ISO8601 subset
const sqliteDatetimeFormat = "2006-01-02 15:04:05.999"
const sqliteDateFormat = "2006-01-02"

func formatSqliteDatetime(t *time.Time) *string {
	s := t.UTC().Format(sqliteDatetimeFormat)
	return &s
}

ctx.ResultDatetime(time.Now())
ctx.ResultDate(time.Now())
ctx.ResultDate(time.Date(2000, 1, 1))
```

I'm less sure about this solution, because time/UTC confuses me... 

---

Again, would be happy to put up a PR if you'd like these APIs! I could see an argument be made that this library should be as close to the C API as possible and adding json/date/booleans would be weird, but there's a definitely productivity boost to be gained by some of these.

**Comment by riyaz-ali** [comment]
Hey @asg017! Those are indeed very helpful suggestions 😃 

I like the idea of having a `ctx.ResultBool()` function. It sort of makes the API complete, in the sense that we'll support all `go` primitive types. I'd be happy to include it with the library 👍 

For the rest, I kind of have mixed feelings. On the one hand, I can see why these types would be useful; since `json` and `time` handling are very frequent operations. But on the other hand, we'd diverge away from sqlite3's C API. Also, automatically setting the sub-type [for json] is helpful, but can quickly become _magical_ for the uninitiated user.

Rather than this, I suggest if we can work towards adding more documentation and snippets describing common patterns and how-tos. Let me know your thoughts on this.

**Comment by riyaz-ali** [comment]
Added these recipes to `docs/RECIPES.md` 🙌
