### ISSUE TITLE
Closing sqlite after failing to load an extension gets stuck

### ISSUE THREAD

**Issue by anacrolix** [riyaz-ali/sqlite#14]
If I try to register something (say a Function that doesn't implement the correct interface) and there's an error, sqlite seems to get stuck when exiting and CPU goes to ~500%+. I suspect there's some cleanup logic that's wrong. I saw it previously with other registration errors, but naturally fixing those makes it go away because I don't normally aim to have errors during registration.

**Comment by riyaz-ali** [comment]
I've run into several cases where the registration would fail, but sqlite would return the error (either from `sqlite3_open()` or `sqlite3_load_extension()`) and exit cleanly. Can you share some more detail of where it fails / gets stuck?

**Comment by anacrolix** [comment]
I think it could be due to the 2 runtimes I described here: https://github.com/riyaz-ali/sqlite/issues/16#issuecomment-1289836157. I will close it and reopen it if I see the problem again.
