### ISSUE TITLE
Add examples and documentation

### ISSUE THREAD

**Issue by riyaz-ali** [riyaz-ali/sqlite#2]
This issue tracks the progress towards having a better documentation completed with proper examples and sample use cases.

**Comment by anacrolix** [comment]
One such case is [linked statically at build-time](https://github.com/riyaz-ali/sqlite#overview). Are you using that case downstream? I messed about with it and might have some contributions to fix it up if I'm not already doing it incorrectly, it seemed to work as an alternative to [loading a Go DLL from Go](https://github.com/riyaz-ali/sqlite/issues/16).

**Comment by riyaz-ali** [comment]
You can checkout [`mergestat/mergestat-lite`](/mergestat/mergestat-lite). There, the bulk of the functionality is implemented as `sqlite3` Virtual Table and bundled as an extension (under [`/extensions`](/mergestat/mergestat-lite/tree/main/extensions) directory). The extension is then statically linked into the final executable.

Specific point-of interests in that repository would be:

- [`/pkg/sqlite/sqlite.go`](https://github.com/mergestat/mergestat-lite/blob/main/pkg/sqlite/sqlite.go) where the extension is setup to [load automatically for each connection](https://www.sqlite.org/c3ref/auto_extension.html). This package also contains the `sqlite3` amalgamation source.

- [`/cmd/setup.go`](https://github.com/mergestat/mergestat-lite/blob/main/cmd/setup.go#L10-L14) where the package is linked to the main application (using side-effect import).

- [`/Makefile`](https://github.com/mergestat/mergestat-lite/blob/main/Makefile#L6-L12) that contains the relevant linker flags to allow compiling the intermediate object files with unresolved symbols (this is to workaround the way `go build` works for `cgo`)

---------------------

I agree at this point all this is _tribal knowledge_ that we all have learnt and discovered through trial and error, and needs to be better documented somewhere 😅

**Comment by anacrolix** [comment]
That's interesting. I have left compilation of sqlite.c to the driver I'm using (crawshaw.io/sqlite), and [made your lib build with `SQLITE_CORE`](https://github.com/riyaz-ali/sqlite/compare/master...anacrolix:riyaz-ali-sqlite:master#diff-6e85f2eac7709f47bedbef3aa142aec00dfaf6886fa021c32f7e1efb363fe9daR6) so it doesn't try to initialize sqlite again. Then I pass the [C `sqlite3` handle from crawshaw.io/sqlite](https://github.com/crawshaw/sqlite/compare/master...anacrolix:crawshaw-sqlite:master#diff-3101fd8b5ebefc9739f7efdafa4dd6f04c19db98fc4428623ee619a2773c8501R90-R93) to my register function [at the Go level](https://github.com/riyaz-ali/sqlite/compare/master...anacrolix:riyaz-ali-sqlite:master#diff-4b91b85dc5ac087a0f02569a3f80b27bd73cb8d30e5cd4d31c4b93ebdf2d8c12R58-R63) (and it calls `ExtensionApi.*` for all the stuff it needs to set up).

I'm not sure why the static tag works for you, the [errant sqlite3ext build tag](https://github.com/riyaz-ali/sqlite/blob/77a6464e0c2a5cc69cb7d67240f47f77f5bc2065/static.go#L2) caused problems for me I think.

**Comment by riyaz-ali** [comment]
@anacrolix I've moved this discussion (around static-linked extension) to #18 . Let's continue with it there.
