### ISSUE TITLE
Fix Makefile to generate static library and instructions for building extension wrapper for asg017/sqlite-http and asg017/sqlite-html

### ISSUE THREAD

**Issue by avinashkurup** [riyaz-ali/sqlite#23]
## Description
Running `make vet` on the project surfaces warnings about potential misuse of `reflect.SliceHeader` in multiple files. These instances may lead to unsafe behavior and need to be addressed to ensure memory safety.

Additionally, there is a lack of clear instructions for building static libraries for Linux, Windows, and macOS. These are necessary for creating an executable that integrates `sqlite-http`, `sqlite-html`, and other SQLite extensions into the SQLite amalgamation.

## Issues to Address

1. **Misuse of `reflect.SliceHeader`**: The `reflect.SliceHeader` is used unsafely in the following files, which may lead to memory misalignment, data corruption, and garbage collection issues:

   - `func.go:143:39`
   - `stmt.go:409:40`
   - `virtual_table.go:496:44`
   - `virtual_table.go:533:70`
   - `virtual_table.go:546:67`
   - `virtual_table.go:574:75`
   - `virtual_table.go:868:38`

   These instances should be refactored using safe conversion functions provided by the `reflect` package.

2. **Static Library Build Instructions**: The project needs detailed instructions for building static libraries compatible with Linux, Windows, and macOS. This is crucial for users attempting to compile a customized build of sqlite3 that includes the `sqlite-http`, `sqlite-html`, and other extensions.

## Expected Outcome

- Refactored code that removes unsafe usage of `reflect.SliceHeader` and adheres to Go's safety guidelines.
- Comprehensive build instructions for generating static libraries across different operating systems.

Your assistance in resolving these issues would be highly appreciated as they are critical for the development of a stable and secure customized SQLite build.

Thank you.
Avinash.

**Comment by avinashkurup** [comment]
Great to hear that the reflect.SliceHeader issue is being addressed. Now, regarding the second query on building a static library for Linux, Windows, and Mac, Please give me instructions to compile the sqlite-http and sqlite-html extensions as a static library and link with the SQLite amalgamation into a single executable.

**Comment by avinashkurup** [comment]
Hi,
    Please direct me to instructions to use this sqlite extension as a static library and integrate the asg017/http and asg017/html extensions with this project. I am able to run the html go extension as a static library but face issues with the http extension as explained in the ticket https://github.com/asg017/sqlite-http/issues/32.
    Any help would be greatly appretiated

**Comment by riyaz-ali** [comment]
Hi @avinashkurup!

> Running `make vet` on the project surfaces warnings about potential misuse of `reflect.SliceHeader` in multiple files. 

I started working on it in #22 but haven't got the time to finish it off yet.

> Additionally, there is a lack of clear instructions for building static libraries for Linux, Windows, and macOS.

You can find instructions on statically linking extensions built with this library at [`docs/STATIC_LINKING.md`](https://github.com/riyaz-ali/sqlite/blob/832d6b745bcd7f7302541fab7ba832b41a2fefba/docs/STATIC_LINKING.md). I've tried the steps on both macOs and Linux, but I'm not sure about Windows.

> I see that the Makefile has only targets to run vet and tests, can you add targets to build this extension as a static library by invoking the Makefile?

Sorry, but we can't really add `Makefile` targets for downstream projects here. Those targets and build steps belong to the projects and are not related to this library.
